// <auto-generated />
using System;
using FeriadosNacionaisAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(FeriadosDbContext))]
    [Migration("20250618214222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Feriado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Counties")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Fixed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Global")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LaunchYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Types")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feriados");
                });
#pragma warning restore 612, 618
        }
    }
}
